<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />


<meta name="author" content="Philipp Broniecki and Lucas Leemann – Machine Learning 1K" />


<title>Solution Day 3 Lab - Classification</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/sandstone.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-1.1/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-1.1/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs && document.readyState && document.readyState === "complete") {
   window.setTimeout(function() {
      hljs.initHighlighting();
   }, 0);
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="styles.css" type="text/css" />

</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 61px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 66px;
  margin-top: -66px;
}

.section h2 {
  padding-top: 66px;
  margin-top: -66px;
}
.section h3 {
  padding-top: 66px;
  margin-top: -66px;
}
.section h4 {
  padding-top: 66px;
  margin-top: -66px;
}
.section h5 {
  padding-top: 66px;
  margin-top: -66px;
}
.section h6 {
  padding-top: 66px;
  margin-top: -66px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->






<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Essex 2017 Machine Learning</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Day 1
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="day1.html">Lab</a>
    </li>
    <li>
      <a href="./slides/D1%20-%20Intro%20ML.pdf">Slides</a>
    </li>
    <li>
      <a href="solutions1.html">Solutions</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Day 2
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="day2.html">Lab</a>
    </li>
    <li>
      <a href="./slides/D2%20-%20Intro%20ML.pdf">Slides</a>
    </li>
    <li>
      <a href="solutions2.html">Solutions</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Day 3
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="day3.html">Lab</a>
    </li>
    <li>
      <a href="./slides/D3%20-%20Classification.pdf">Slides</a>
    </li>
    <li>
      <a href="solutions3.html">Solutions</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Day 4
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="day4.html">Lab</a>
    </li>
    <li>
      <a href="./slides/D4%20-%20Resampling.pdf">Slides</a>
    </li>
    <li>
      <a href="solutions4.html">Solutions</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Day 5
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="day5.html">Lab</a>
    </li>
    <li>
      <a href="labs/Lab%20Code%205.R">plain R-Code</a>
    </li>
    <li>
      <a href="./slides/D5%20-%20Model%20Selection%20I.pdf">Slides</a>
    </li>
    <li>
      <a href="solutions5.html">Solutions</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Day 6
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="day6.html">Lab</a>
    </li>
    <li>
      <a href="./slides/D6%20-%20Model%20Selection%20II.pdf">Slides</a>
    </li>
    <li>
      <a href="solutions6.html">Solutions</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Day 7
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="day7.html">Lab</a>
    </li>
    <li>
      <a href="./slides/D7%20-%20Polynomial%20Models.pdf">Slides</a>
    </li>
    <li>
      <a href="solutions7.html">Solutions</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Day 8
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="day8.html">Lab</a>
    </li>
    <li>
      <a href="./slides/D8%20-%20Tree-Based%20Methods.pdf">Slides</a>
    </li>
    <li>
      <a href="solutions8.html">Solutions</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Day 9
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="day9.html">Lab</a>
    </li>
    <li>
      <a href="./slides/D9%20-%20Unsupervised%20Learning.pdf">Slides</a>
    </li>
    <li>
      <a href="solutions9.html">Solutions</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    More
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="simulation.html">Simulation</a>
    </li>
    <li>
      <a href="montecarlo.html">Monte Carlos</a>
    </li>
    <li>
      <a href="MCLassoRidge.html">MC Lasso v. Ridge</a>
    </li>
    <li>
      <a href="./data/titanic.dta">Titanic Data</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Solution Day 3 Lab - Classification</h1>
<h4 class="author"><em>Philipp Broniecki and Lucas Leemann – Machine Learning 1K</em></h4>

</div>


<p>You will need to load the core library for the course textbook:</p>
<pre class="r"><code># clear workspace
rm(list=ls())

library(ISLR)</code></pre>
<div id="q1" class="section level4">
<h4>Q1</h4>
<p>In this problem, you will develop a model to predict whether a given car gets high or low gas mileage based on the <code>Auto</code> dataset from the <code>ISLR</code> package.</p>
<ol style="list-style-type: decimal">
<li>Create a binary variable, <code>mpg01</code>, that contains a 1 if <code>mpg</code> contains a value above its median, and a 0 if <code>mpg</code> contains a value below its median. You can compute the median using the <code>median()</code> function. Note you may find it helpful to use the <code>data.frame()</code> function to create a single data set containing both <code>mpg01</code> and the other <code>Auto</code> variables. Type <code>?Auto</code> to get the codebook of the dataset.</li>
</ol>
<pre class="r"><code>library(ISLR)
summary(Auto)</code></pre>
<pre><code>##       mpg          cylinders      displacement     horsepower   
##  Min.   : 9.00   Min.   :3.000   Min.   : 68.0   Min.   : 46.0  
##  1st Qu.:17.00   1st Qu.:4.000   1st Qu.:105.0   1st Qu.: 75.0  
##  Median :22.75   Median :4.000   Median :151.0   Median : 93.5  
##  Mean   :23.45   Mean   :5.472   Mean   :194.4   Mean   :104.5  
##  3rd Qu.:29.00   3rd Qu.:8.000   3rd Qu.:275.8   3rd Qu.:126.0  
##  Max.   :46.60   Max.   :8.000   Max.   :455.0   Max.   :230.0  
##                                                                 
##      weight      acceleration        year           origin     
##  Min.   :1613   Min.   : 8.00   Min.   :70.00   Min.   :1.000  
##  1st Qu.:2225   1st Qu.:13.78   1st Qu.:73.00   1st Qu.:1.000  
##  Median :2804   Median :15.50   Median :76.00   Median :1.000  
##  Mean   :2978   Mean   :15.54   Mean   :75.98   Mean   :1.577  
##  3rd Qu.:3615   3rd Qu.:17.02   3rd Qu.:79.00   3rd Qu.:2.000  
##  Max.   :5140   Max.   :24.80   Max.   :82.00   Max.   :3.000  
##                                                                
##                  name    
##  amc matador       :  5  
##  ford pinto        :  5  
##  toyota corolla    :  5  
##  amc gremlin       :  4  
##  amc hornet        :  4  
##  chevrolet chevette:  4  
##  (Other)           :365</code></pre>
<pre class="r"><code>attach(Auto)
mpg01 &lt;- ifelse( mpg &gt; median(mpg), yes = 1, no = 0)
Auto &lt;- data.frame(Auto, mpg01)</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>Explore the data graphically in order to investigate the association between <code>mpg01</code> and the other features. Which of the other features seem most likely to be useful in predicting <code>mpg01</code>? Scatterplots and boxplots may be useful tools to answer this question. Describe your findings.</li>
</ol>
<pre class="r"><code>cor(Auto[,-9])</code></pre>
<pre><code>##                     mpg  cylinders displacement horsepower     weight
## mpg           1.0000000 -0.7776175   -0.8051269 -0.7784268 -0.8322442
## cylinders    -0.7776175  1.0000000    0.9508233  0.8429834  0.8975273
## displacement -0.8051269  0.9508233    1.0000000  0.8972570  0.9329944
## horsepower   -0.7784268  0.8429834    0.8972570  1.0000000  0.8645377
## weight       -0.8322442  0.8975273    0.9329944  0.8645377  1.0000000
## acceleration  0.4233285 -0.5046834   -0.5438005 -0.6891955 -0.4168392
## year          0.5805410 -0.3456474   -0.3698552 -0.4163615 -0.3091199
## origin        0.5652088 -0.5689316   -0.6145351 -0.4551715 -0.5850054
## mpg01         0.8369392 -0.7591939   -0.7534766 -0.6670526 -0.7577566
##              acceleration       year     origin      mpg01
## mpg             0.4233285  0.5805410  0.5652088  0.8369392
## cylinders      -0.5046834 -0.3456474 -0.5689316 -0.7591939
## displacement   -0.5438005 -0.3698552 -0.6145351 -0.7534766
## horsepower     -0.6891955 -0.4163615 -0.4551715 -0.6670526
## weight         -0.4168392 -0.3091199 -0.5850054 -0.7577566
## acceleration    1.0000000  0.2903161  0.2127458  0.3468215
## year            0.2903161  1.0000000  0.1815277  0.4299042
## origin          0.2127458  0.1815277  1.0000000  0.5136984
## mpg01           0.3468215  0.4299042  0.5136984  1.0000000</code></pre>
<pre class="r"><code>pairs(Auto) # doesn&#39;t work well since mpg01 is 0 or 1</code></pre>
<p><img src="solutions3_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p><strong>cylinders, weight, displacement, horsepower (and mpg itself)</strong></p>
<ol start="3" style="list-style-type: decimal">
<li>Split the data into a training set and a test set.</li>
</ol>
<p>First, we normalize our varibles</p>
<pre class="r"><code>Auto &lt;- data.frame(mpg01, apply(cbind(cylinders, weight, displacement, horsepower, acceleration), 
                                2, scale), year)</code></pre>
<p>We use the <code>%%</code> operator to split the data set into observations with even and uneven years. Check <a href="%22http://www.statmethods.net/management/operators.html%22">here</a> for a description of different R operators.</p>
<pre class="r"><code>train &lt;-  (year %% 2 == 0) # if the year is even (%%)
test &lt;-  !train
Auto.train &lt;-  Auto[train,]
Auto.test &lt;-  Auto[test,]
mpg01.test &lt;-  mpg01[test]</code></pre>
<ol start="4" style="list-style-type: decimal">
<li>Perform LDA on the training data in order to predict <code>mpg01</code> using the variables that seemed most associated with <code>mpg01</code> in (b). What is the test error of the model obtained?</li>
</ol>
<pre class="r"><code># LDA
library(MASS)
lda.fit &lt;-  lda(mpg01 ~ cylinders + weight + displacement + horsepower,
              data = Auto, subset = train)
lda.pred &lt;-  predict(lda.fit, Auto.test)
mean(lda.pred$class != mpg01.test)</code></pre>
<pre><code>## [1] 0.1263736</code></pre>
<p><strong>12.6% test error rate.</strong></p>
<ol start="5" style="list-style-type: decimal">
<li>Perform logistic regression on the training data in order to predict <code>mpg01</code> using the variables that seemed most associated with <code>mpg01</code> in (b). What is the test error of the model obtained?</li>
</ol>
<pre class="r"><code># Logistic regression
glm.fit &lt;-  glm(mpg01 ~ cylinders + weight + displacement + horsepower,
              data = Auto,
              family = binomial,
              subset = train)
glm.probs &lt;-  predict(glm.fit, Auto.test, type = &quot;response&quot;)
glm.pred &lt;-  rep(0, length(glm.probs))
glm.pred[glm.probs &gt; 0.5] &lt;- 1
mean(glm.pred != mpg01.test)</code></pre>
<pre><code>## [1] 0.1208791</code></pre>
<p><strong>12.1% test error rate.</strong></p>
<ol start="6" style="list-style-type: decimal">
<li>Perform KNN on the training data, with several values of K, in order to predict <code>mpg01</code>. Use only the variables that seemed most associated with <code>mpg01</code> in (b). What test errors do you obtain? Which value of K seems to perform the best on this data set?</li>
</ol>
<pre class="r"><code>library(class)
train.X &lt;-  cbind(cylinders, weight, displacement, horsepower)[train,]
test.X &lt;-  cbind(cylinders, weight, displacement, horsepower)[test,]
train.mpg01 &lt;-  mpg01[train]
set.seed(1)

# KNN (k=1)
knn.pred &lt;-  knn(train.X, test.X, train.mpg01, k = 1)
mean(knn.pred != mpg01.test)</code></pre>
<pre><code>## [1] 0.1538462</code></pre>
<pre class="r"><code># KNN (k=10)
knn.pred &lt;-  knn(train.X, test.X, train.mpg01, k = 10)
mean(knn.pred != mpg01.test)</code></pre>
<pre><code>## [1] 0.1648352</code></pre>
<pre class="r"><code># KNN (k=100)
knn.pred &lt;-  knn(train.X, test.X, train.mpg01, k = 100)
mean(knn.pred != mpg01.test)</code></pre>
<pre><code>## [1] 0.1428571</code></pre>
<p><strong>k=1, 15.4% test error rate. k=10, 16.5% test error rate. k=100, 14.3% test error rate. K of 100 seems to perform the best. 100 nearest neighbors.</strong></p>
<ol start="7" style="list-style-type: decimal">
<li>We can find the optimal value for K by trying all K from 1 to 200. We will run a loop and save the test error for every value of K.</li>
</ol>
<pre class="r"><code>K.collector &lt;- rep(NA, 200)
for (k.try in 1:200){
  knn.pred &lt;-  knn(train.X, test.X, train.mpg01, k = k.try)
  K.collector[k.try] &lt;- mean(knn.pred != mpg01.test)
}
x.k &lt;- c(1:200)

plot(x.k,K.collector, type=&quot;o&quot;, pch=19, cex=0.5, main=&quot;K &quot;)</code></pre>
<p><img src="solutions3_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>It is hard to see the optimal value of K for us. We can inspect the error ourselves:</p>
<pre class="r"><code>which.min(K.collector)</code></pre>
<pre><code>## [1] 4</code></pre>
<p><strong>Here, it seems to be the case that K=4 is the best. We will see tomorrow how we can ensure that this does not just depend on the specific trianing and test data we created here.</strong></p>
</div>
<div id="q2" class="section level4">
<h4>Q2</h4>
<p>This problem involves writing functions.</p>
<ol style="list-style-type: decimal">
<li>Write a function, <code>Power()</code>, that prints out the result of raising 2 to the 3rd power. In other words, your function should compute <span class="math inline">\(2^3\)</span> and print out the results.</li>
</ol>
<p>Hint: Recall that <span class="math inline">\(x^a\)</span> raises x to the power a. Use the <code>print()</code> function to output the result.</p>
<pre class="r"><code>Power &lt;-  function() {
  2^3
}
print(Power())</code></pre>
<pre><code>## [1] 8</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>Create a new function, <code>Power2()</code>, that allows you to pass any two numbers, <code>x</code> and <code>a</code>, and prints out the value of <code>x^a</code>. You can do this by beginning your function with the line:</li>
</ol>
<pre class="r"><code>Power2 &lt;- function(x,a) {</code></pre>
<p>You should be able to call your function by entering, for instance,</p>
<pre class="r"><code>Power2(3,8)</code></pre>
<p>on the command line. This should output the value of <span class="math inline">\(3^8\)</span>, namely, 6,561.</p>
<pre class="r"><code>Power2 &lt;-  function(x, a) {
  x^a
}
Power2(3,8)</code></pre>
<pre><code>## [1] 6561</code></pre>
<ol start="3" style="list-style-type: decimal">
<li>Using the <code>Power2()</code> function that you just wrote, compute <span class="math inline">\(10^3\)</span>, <span class="math inline">\(8^{17}\)</span>, and <span class="math inline">\(131^3\)</span>.</li>
</ol>
<pre class="r"><code>Power2(10, 3)</code></pre>
<pre><code>## [1] 1000</code></pre>
<pre class="r"><code>Power2(8, 17)</code></pre>
<pre><code>## [1] 2.2518e+15</code></pre>
<pre class="r"><code>Power2(131, 3)</code></pre>
<pre><code>## [1] 2248091</code></pre>
<ol start="4" style="list-style-type: decimal">
<li>Now create a new function, <code>Power3()</code>, that actually returns the result <code>x^a</code> as an R object, rather than simply printing it to the screen. That is, if you store the value <code>x^a</code> in an object called result within your function, then you can simply <code>return()</code> this result, using the following line:</li>
</ol>
<pre class="r"><code>return(result)</code></pre>
<p>The line above should be the last line in your function, before the <code>}</code> symbol.</p>
<pre class="r"><code>Power3 &lt;-  function(x, a) {
  result &lt;-  x^a
  return(result)
}</code></pre>
<ol start="5" style="list-style-type: decimal">
<li>Now using the <code>Power3()</code> function, create a plot of <span class="math inline">\(f(x)=x^2\)</span>. The <span class="math inline">\(x\)</span>-axis should display a range of integers from 1 to 10, and the <span class="math inline">\(y\)</span>-axis should display <span class="math inline">\(x^2\)</span>. Label the axes appropriately, and use an appropriate title for the figure. Consider displaying either the <span class="math inline">\(x\)</span>-axis, the <span class="math inline">\(y\)</span>-axis, or both on the log-scale. You can do this by using <code>log=&quot;x&quot;</code>, <code>log=&quot;y&quot;</code>, or <code>log=&quot;xy&quot;</code> as arguments to the <code>plot()</code> function.</li>
</ol>
<pre class="r"><code>x &lt;-  1:10
plot(x, Power3(x, 2),  
     log=&quot;xy&quot;, ylab=&quot;Log of y = x^2&quot;, xlab=&quot;Log of x&quot;, 
     main=&quot;Log of x^2 versus Log of x&quot;, bty = &quot;n&quot;)</code></pre>
<p><img src="solutions3_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<ol start="6" style="list-style-type: decimal">
<li>Create a function, <code>PlotPower()</code>, that allows you to create a plot of <code>x</code> against <code>x^a</code> for a fixed <code>a</code> and for a range of values of <code>x</code>. For instance, if you call</li>
</ol>
<pre class="r"><code>PlotPower(1:10, 3)</code></pre>
<p>then a plot should be created with an <span class="math inline">\(x\)</span>-axis taking on values <span class="math inline">\(1,2,...,10\)</span>, and a <span class="math inline">\(y\)</span>-axis taking on values <span class="math inline">\(1^3,2^3,...,10^3\)</span>.</p>
<pre class="r"><code>PlotPower &lt;-  function(x, a) {
  plot(x, Power3(x, a), bty = &quot;n&quot;)
}
PlotPower(1:10, 3)</code></pre>
<p><img src="solutions3_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
